// <auto-generated />
using System;
using Betterfit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Betterfit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416214001_AddGymSales")]
    partial class AddGymSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Betterfit.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.AuthenticationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Type");

                    b.ToTable("AuthenticationChallenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuthenticationChallenges_CodeExpiryByType", "(\"Type\" = 'EmailVerification' AND \"CodeExpiresAtUtc\" IS NOT NULL) OR (\"Type\" <> 'EmailVerification' AND \"CodeExpiresAtUtc\" IS NULL)");

                            t.HasCheckConstraint("CK_AuthenticationChallenges_CodeExpiryWithinSession", "\"CodeExpiresAtUtc\" IS NULL OR \"CodeExpiresAtUtc\" <= \"SessionExpiresAtUtc\"");
                        });
                });

            modelBuilder.Entity("Betterfit.Models.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Gyms", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymAuthenticationPolicy", b =>
                {
                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequireTwoFactorForMembers")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireTwoFactorForStaff")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GymId");

                    b.ToTable("GymAuthenticationPolicies", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GymMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("GymMembershipId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("GymInvitations", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "Code")
                        .IsUnique();

                    b.HasIndex("GymId", "Name")
                        .IsUnique();

                    b.ToTable("GymLocations", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvitationEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MemberProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("PendingDateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("PendingEmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PendingEmergencyContactPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PendingFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PendingLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PendingPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PrimaryLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.HasIndex("PrimaryLocationId");

                    b.HasIndex("UserId");

                    b.HasIndex("GymId", "InvitationEmail")
                        .IsUnique();

                    b.HasIndex("GymId", "UserId")
                        .IsUnique();

                    b.ToTable("GymMemberships", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymMembershipLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("GymMembershipId", "LocationId")
                        .IsUnique();

                    b.ToTable("GymMembershipLocations", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("GymRoles", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GymMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SoldAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("GymId", "ReferenceCode")
                        .IsUnique();

                    b.HasIndex("GymId", "SoldAtUtc");

                    b.HasIndex("GymMembershipId", "SoldAtUtc");

                    b.ToTable("GymSales", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymSaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CreditsGranted")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("GymSaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ServicePeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ServicePeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GymSaleId");

                    b.ToTable("GymSaleLines", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.GymSalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymSaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GymSaleId");

                    b.ToTable("GymSalePayments", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.MemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MemberProfiles", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.PermissionCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NormalizedAction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedResource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedResource", "NormalizedAction")
                        .IsUnique();

                    b.ToTable("PermissionCatalogItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1015f36b-e0c6-4cd7-88fc-3b2e25572c80"),
                            Action = "read",
                            Description = "View tenant records",
                            NormalizedAction = "READ",
                            NormalizedResource = "GYMS",
                            Resource = "gyms"
                        },
                        new
                        {
                            Id = new Guid("9d56e44c-0117-4f5c-9c53-33257c380389"),
                            Action = "write",
                            Description = "Create or update tenant records",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "GYMS",
                            Resource = "gyms"
                        },
                        new
                        {
                            Id = new Guid("32291f01-7fe4-44cf-9f1c-82bbf8a37295"),
                            Action = "read",
                            Description = "View member data",
                            NormalizedAction = "READ",
                            NormalizedResource = "MEMBERS",
                            Resource = "members"
                        },
                        new
                        {
                            Id = new Guid("f2895883-e3b6-4f31-95ba-e8aa183d9a31"),
                            Action = "write",
                            Description = "Create or update members",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "MEMBERS",
                            Resource = "members"
                        },
                        new
                        {
                            Id = new Guid("f4146dab-43bc-494c-86d2-c0256744996a"),
                            Action = "read",
                            Description = "View tenant staff assignments",
                            NormalizedAction = "READ",
                            NormalizedResource = "STAFF_ASSIGNMENTS",
                            Resource = "staff_assignments"
                        },
                        new
                        {
                            Id = new Guid("98b12021-bad0-49ec-bd1f-2d8d4e9b3f81"),
                            Action = "write",
                            Description = "Create or update tenant staff assignments",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "STAFF_ASSIGNMENTS",
                            Resource = "staff_assignments"
                        },
                        new
                        {
                            Id = new Guid("aa09dba0-1f46-4197-a8e2-445c10d737f6"),
                            Action = "read",
                            Description = "View role definitions",
                            NormalizedAction = "READ",
                            NormalizedResource = "ROLES",
                            Resource = "roles"
                        },
                        new
                        {
                            Id = new Guid("f3dce9e8-6d98-40df-a312-3152f3248e09"),
                            Action = "write",
                            Description = "Create or update role definitions",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "ROLES",
                            Resource = "roles"
                        },
                        new
                        {
                            Id = new Guid("c7c46676-f643-4d17-b541-7d81dcbca635"),
                            Action = "read",
                            Description = "View billing information",
                            NormalizedAction = "READ",
                            NormalizedResource = "BILLING",
                            Resource = "billing"
                        },
                        new
                        {
                            Id = new Guid("c04e4eef-c5f7-42b0-a820-c50a3978d19f"),
                            Action = "write",
                            Description = "Modify billing information",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "BILLING",
                            Resource = "billing"
                        },
                        new
                        {
                            Id = new Guid("27ecb0f0-4862-45eb-9b9f-2ca9505855f4"),
                            Action = "approve",
                            Description = "Approve plans and subscriptions",
                            NormalizedAction = "APPROVE",
                            NormalizedResource = "PLANS",
                            Resource = "plans"
                        },
                        new
                        {
                            Id = new Guid("4f0409b0-c0f2-47cb-94dd-722efcc5e847"),
                            Action = "read",
                            Description = "View class schedules",
                            NormalizedAction = "READ",
                            NormalizedResource = "CLASSES",
                            Resource = "classes"
                        },
                        new
                        {
                            Id = new Guid("c8e7699f-f64f-4578-9a8a-e486e3fd7f95"),
                            Action = "write",
                            Description = "Create or update class schedules",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "CLASSES",
                            Resource = "classes"
                        },
                        new
                        {
                            Id = new Guid("e00a4ee3-ec77-4030-8df3-31616b19226a"),
                            Action = "export",
                            Description = "Export reports",
                            NormalizedAction = "EXPORT",
                            NormalizedResource = "REPORTS",
                            Resource = "reports"
                        },
                        new
                        {
                            Id = new Guid("ea2b1144-a8f9-4f15-8afa-4fcf60ecaf50"),
                            Action = "read",
                            Description = "View workout plans",
                            NormalizedAction = "READ",
                            NormalizedResource = "WORKOUTS",
                            Resource = "workouts"
                        },
                        new
                        {
                            Id = new Guid("132f89ad-c2de-4f84-93af-8619d30fca0d"),
                            Action = "write",
                            Description = "Create or update workout plans",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "WORKOUTS",
                            Resource = "workouts"
                        },
                        new
                        {
                            Id = new Guid("de2a4fcb-13dd-4a8f-b435-5f1f0ca10961"),
                            Action = "read",
                            Description = "View own profile",
                            NormalizedAction = "READ",
                            NormalizedResource = "PROFILE",
                            Resource = "profile"
                        },
                        new
                        {
                            Id = new Guid("93a83f38-69ef-4637-ae5f-7ec42b17dcb6"),
                            Action = "write",
                            Description = "Update own profile",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "PROFILE",
                            Resource = "profile"
                        },
                        new
                        {
                            Id = new Guid("a5c55147-1d99-433e-b022-5164d7eff76d"),
                            Action = "approve",
                            Description = "Approve member check-ins",
                            NormalizedAction = "APPROVE",
                            NormalizedResource = "CHECKINS",
                            Resource = "checkins"
                        },
                        new
                        {
                            Id = new Guid("d88d6e31-2f85-4d05-a9bc-802eec0e7846"),
                            Action = "read",
                            Description = "View gym locations",
                            NormalizedAction = "READ",
                            NormalizedResource = "LOCATIONS",
                            Resource = "locations"
                        },
                        new
                        {
                            Id = new Guid("0995f6e7-d10b-486c-8633-b1a6140ea170"),
                            Action = "write",
                            Description = "Create or update gym locations",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "LOCATIONS",
                            Resource = "locations"
                        },
                        new
                        {
                            Id = new Guid("6fcf5996-b724-44aa-bab7-7754505dcf3e"),
                            Action = "read",
                            Description = "View tenant authentication and security policy",
                            NormalizedAction = "READ",
                            NormalizedResource = "SECURITY_POLICY",
                            Resource = "security_policy"
                        },
                        new
                        {
                            Id = new Guid("54e4a2dd-8e6d-4919-b7d6-dd5b7b8ed5f7"),
                            Action = "write",
                            Description = "Create or update tenant authentication and security policy",
                            NormalizedAction = "WRITE",
                            NormalizedResource = "SECURITY_POLICY",
                            Resource = "security_policy"
                        });
                });

            modelBuilder.Entity("Betterfit.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InternalCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffProfiles", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.TenantRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimaryOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GymId")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantRoleAssignments_ActivePrimaryOwnerPerGym")
                        .HasFilter("\"IsPrimaryOwner\" AND \"Status\" = 'Active' AND \"RevokedAtUtc\" IS NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScopeLocationId");

                    b.HasIndex("StaffProfileId");

                    b.HasIndex("UserId");

                    b.HasIndex("GymId", "UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantRoleAssignments_TenantScopeUnique")
                        .HasFilter("\"ScopeType\" = 'Tenant' AND \"ScopeLocationId\" IS NULL AND \"Status\" = 'Active' AND \"RevokedAtUtc\" IS NULL");

                    b.HasIndex("GymId", "UserId", "RoleId", "ScopeLocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantRoleAssignments_LocationScopeUnique")
                        .HasFilter("\"ScopeType\" = 'Location' AND \"ScopeLocationId\" IS NOT NULL AND \"Status\" = 'Active' AND \"RevokedAtUtc\" IS NULL");

                    b.ToTable("TenantRoleAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_TenantRoleAssignments_PrimaryOwnerScope", "NOT \"IsPrimaryOwner\" OR (\"ScopeType\" = 'Tenant' AND \"ScopeLocationId\" IS NULL)");

                            t.HasCheckConstraint("CK_TenantRoleAssignments_ScopeConsistency", "(\"ScopeType\" = 'Tenant' AND \"ScopeLocationId\" IS NULL) OR (\"ScopeType\" = 'Location' AND \"ScopeLocationId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Betterfit.Models.AuthenticationChallenge", b =>
                {
                    b.HasOne("Betterfit.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Betterfit.Models.GymAuthenticationPolicy", b =>
                {
                    b.HasOne("Betterfit.Models.Gym", "Gym")
                        .WithOne("AuthenticationPolicy")
                        .HasForeignKey("Betterfit.Models.GymAuthenticationPolicy", "GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("Betterfit.Models.GymInvitation", b =>
                {
                    b.HasOne("Betterfit.Models.Gym", "Gym")
                        .WithMany("Invitations")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.GymMembership", "GymMembership")
                        .WithMany("Invitations")
                        .HasForeignKey("GymMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("GymMembership");
                });

            modelBuilder.Entity("Betterfit.Models.GymLocation", b =>
                {
                    b.HasOne("Betterfit.Models.Gym", "Gym")
                        .WithMany("Locations")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("Betterfit.Models.GymMembership", b =>
                {
                    b.HasOne("Betterfit.Models.Gym", "Gym")
                        .WithMany("Memberships")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.MemberProfile", "MemberProfile")
                        .WithMany("GymMemberships")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Betterfit.Models.GymLocation", "PrimaryLocation")
                        .WithMany("PrimaryMemberships")
                        .HasForeignKey("PrimaryLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Betterfit.Models.ApplicationUser", "User")
                        .WithMany("GymMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Gym");

                    b.Navigation("MemberProfile");

                    b.Navigation("PrimaryLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Betterfit.Models.GymMembershipLocation", b =>
                {
                    b.HasOne("Betterfit.Models.GymMembership", "GymMembership")
                        .WithMany("Locations")
                        .HasForeignKey("GymMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.GymLocation", "Location")
                        .WithMany("Memberships")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymMembership");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Betterfit.Models.GymRole", b =>
                {
                    b.HasOne("Betterfit.Models.Gym", "Gym")
                        .WithMany("Roles")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("Betterfit.Models.GymSale", b =>
                {
                    b.HasOne("Betterfit.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedSales")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.Gym", "Gym")
                        .WithMany("Sales")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.GymMembership", "Membership")
                        .WithMany("Sales")
                        .HasForeignKey("GymMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.GymLocation", "Location")
                        .WithMany("Sales")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Gym");

                    b.Navigation("Location");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Betterfit.Models.GymSaleLine", b =>
                {
                    b.HasOne("Betterfit.Models.GymSale", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("GymSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Betterfit.Models.GymSalePayment", b =>
                {
                    b.HasOne("Betterfit.Models.GymSale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("GymSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Betterfit.Models.MemberProfile", b =>
                {
                    b.HasOne("Betterfit.Models.ApplicationUser", "User")
                        .WithOne("MemberProfile")
                        .HasForeignKey("Betterfit.Models.MemberProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Betterfit.Models.RolePermission", b =>
                {
                    b.HasOne("Betterfit.Models.PermissionCatalogItem", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.GymRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Betterfit.Models.StaffProfile", b =>
                {
                    b.HasOne("Betterfit.Models.ApplicationUser", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("Betterfit.Models.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Betterfit.Models.TenantRoleAssignment", b =>
                {
                    b.HasOne("Betterfit.Models.Gym", "Gym")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.GymRole", "Role")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.GymLocation", "ScopeLocation")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("ScopeLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Betterfit.Models.StaffProfile", "StaffProfile")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.ApplicationUser", "User")
                        .WithMany("TenantRoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Role");

                    b.Navigation("ScopeLocation");

                    b.Navigation("StaffProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Betterfit.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Betterfit.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Betterfit.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Betterfit.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Betterfit.Models.ApplicationUser", b =>
                {
                    b.Navigation("CreatedSales");

                    b.Navigation("GymMemberships");

                    b.Navigation("MemberProfile");

                    b.Navigation("StaffProfile");

                    b.Navigation("TenantRoleAssignments");
                });

            modelBuilder.Entity("Betterfit.Models.Gym", b =>
                {
                    b.Navigation("AuthenticationPolicy");

                    b.Navigation("Invitations");

                    b.Navigation("Locations");

                    b.Navigation("Memberships");

                    b.Navigation("Roles");

                    b.Navigation("Sales");

                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("Betterfit.Models.GymLocation", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("PrimaryMemberships");

                    b.Navigation("Sales");

                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("Betterfit.Models.GymMembership", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Locations");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Betterfit.Models.GymRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("Betterfit.Models.GymSale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Betterfit.Models.MemberProfile", b =>
                {
                    b.Navigation("GymMemberships");
                });

            modelBuilder.Entity("Betterfit.Models.PermissionCatalogItem", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Betterfit.Models.StaffProfile", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
